# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Complete workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: nodets

      - name: Install dependencies
        run: npm install

      - name: Run all tests
        env:
          # MONGO_USER: ${{ secrets.MONGO_USER }}
          # MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          # MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          # MONGO_HOST: ${{ secrets.MONGO_HOST }}
          # MONGO_PORT: ${{ secrets.MONGO_PORT }}
          # MONGO_USER: ${{ secrets.MONGO_USER }}
          # MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE: nodets
          MONGO_HOST: localhost
          MONGO_PORT: 27017
        

        run: npm run test:functional
#
#      - name: Deploy application
#        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "app"
#          heroku_email: "email"
#          buildpack: "https://github.com/zidizei/heroku-buildpack-tsc#v2.0"
